# .github/workflows/epos-automation.yml
name: エポス自動取得
on:
  schedule:
    # 毎日午前9時（日本時間）に実行
    - cron: '0 0 * * *'  # UTCなので日本時間-9時間
  workflow_dispatch:  # 手動実行ボタンも追加

jobs:
  epos-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v3
      
    - name: Python環境をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 必要なライブラリをインストール
      run: |
        pip install selenium pandas gspread google-auth requests beautifulsoup4
        
    - name: Google Chromeをインストール
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: ChromeDriverをインストール
      uses: nanasess/setup-chromedriver@master
        
    - name: エポス自動処理を実行
      env:
        EPOS_USERNAME: ${{ secrets.EPOS_USERNAME }}
        EPOS_PASSWORD: ${{ secrets.EPOS_PASSWORD }}
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python epos_automation.py
      
    - name: 実行結果をアップロード
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs
        path: logs/
